{"timestamp": "2024-11-09T23:14:46.579643", "level": "WARNING", "logger": "flawless_api", "message": "Failed to generate API docs for /_metrics: 'NoneType' object is not iterable", "module": "router", "line": 490}
{"timestamp": "2024-11-09T23:14:46.581640", "level": "WARNING", "logger": "flawless_api", "message": "Failed to generate API docs for /_traces: 'NoneType' object is not iterable", "module": "router", "line": 490}
{"timestamp": "2024-11-09T23:14:46.582635", "level": "WARNING", "logger": "flawless_api", "message": "Failed to generate API docs for /_health: 'NoneType' object is not iterable", "module": "router", "line": 490}
{"timestamp": "2024-11-09T23:14:46.584628", "level": "WARNING", "logger": "flawless_api", "message": "Failed to generate API docs for /_info: 'NoneType' object is not iterable", "module": "router", "line": 490}
{"timestamp": "2024-11-09T23:14:46.585630", "level": "WARNING", "logger": "flawless_api", "message": "Failed to generate API docs for /users/{id}: 'NoneType' object is not iterable", "module": "router", "line": 490}
{"timestamp": "2024-11-09T23:14:46.586630", "level": "WARNING", "logger": "flawless_api", "message": "Failed to generate API docs for /users: 'NoneType' object is not iterable", "module": "router", "line": 490}
{"timestamp": "2024-11-09T23:14:46.587634", "level": "WARNING", "logger": "flawless_api", "message": "Failed to generate API docs for /upload: 'NoneType' object is not iterable", "module": "router", "line": 490}
{"timestamp": "2024-11-09T23:14:46.588629", "level": "WARNING", "logger": "flawless_api", "message": "Failed to generate API docs for /page: 'NoneType' object is not iterable", "module": "router", "line": 490}
{"timestamp": "2024-11-09T23:14:46.589629", "level": "WARNING", "logger": "flawless_api", "message": "Failed to generate API docs for /message: 'NoneType' object is not iterable", "module": "router", "line": 490}
{"timestamp": "2024-11-09T23:14:46.590628", "level": "WARNING", "logger": "flawless_api", "message": "Failed to generate API docs for /tasks: 'NoneType' object is not iterable", "module": "router", "line": 490}
{"timestamp": "2024-11-09T23:14:46.591630", "level": "WARNING", "logger": "flawless_api", "message": "Failed to generate API docs for /docs: 'NoneType' object is not iterable", "module": "router", "line": 490}
{"timestamp": "2024-11-09T23:14:46.592630", "level": "WARNING", "logger": "flawless_api", "message": "Failed to generate API docs for /api/docs/spec: 'NoneType' object is not iterable", "module": "router", "line": 490}
{"timestamp": "2024-11-09T23:17:09.599067", "level": "WARNING", "logger": "flawless_api", "message": "Failed to generate API docs for /_metrics: 'DocstringReturns' object is not iterable", "module": "router", "line": 490}
{"timestamp": "2024-11-09T23:17:09.610696", "level": "WARNING", "logger": "flawless_api", "message": "Failed to generate API docs for /_traces: 'DocstringReturns' object is not iterable", "module": "router", "line": 490}
{"timestamp": "2024-11-09T23:17:09.612691", "level": "WARNING", "logger": "flawless_api", "message": "Failed to generate API docs for /_health: 'DocstringReturns' object is not iterable", "module": "router", "line": 490}
{"timestamp": "2024-11-09T23:17:09.614689", "level": "WARNING", "logger": "flawless_api", "message": "Failed to generate API docs for /_info: 'DocstringReturns' object is not iterable", "module": "router", "line": 490}
{"timestamp": "2024-11-09T23:17:09.615688", "level": "WARNING", "logger": "flawless_api", "message": "Failed to generate API docs for /users/{id}: 'NoneType' object is not iterable", "module": "router", "line": 490}
{"timestamp": "2024-11-09T23:17:09.616688", "level": "WARNING", "logger": "flawless_api", "message": "Failed to generate API docs for /users: 'NoneType' object is not iterable", "module": "router", "line": 490}
{"timestamp": "2024-11-09T23:17:09.617692", "level": "WARNING", "logger": "flawless_api", "message": "Failed to generate API docs for /upload: 'NoneType' object is not iterable", "module": "router", "line": 490}
{"timestamp": "2024-11-09T23:17:09.618689", "level": "WARNING", "logger": "flawless_api", "message": "Failed to generate API docs for /page: 'NoneType' object is not iterable", "module": "router", "line": 490}
{"timestamp": "2024-11-09T23:17:09.619689", "level": "WARNING", "logger": "flawless_api", "message": "Failed to generate API docs for /message: 'NoneType' object is not iterable", "module": "router", "line": 490}
{"timestamp": "2024-11-09T23:17:09.620688", "level": "WARNING", "logger": "flawless_api", "message": "Failed to generate API docs for /tasks: 'NoneType' object is not iterable", "module": "router", "line": 490}
{"timestamp": "2024-11-09T23:17:09.621689", "level": "WARNING", "logger": "flawless_api", "message": "Failed to generate API docs for /docs: 'NoneType' object is not iterable", "module": "router", "line": 490}
{"timestamp": "2024-11-09T23:17:09.622690", "level": "WARNING", "logger": "flawless_api", "message": "Failed to generate API docs for /api/docs/spec: 'NoneType' object is not iterable", "module": "router", "line": 490}
{"timestamp": "2024-11-09T23:18:52.029508", "level": "WARNING", "logger": "flawless_api", "message": "Failed to generate API docs for /_metrics: 'DocstringReturns' object is not iterable", "module": "router", "line": 490, "exception": {"type": "TypeError", "message": "'DocstringReturns' object is not iterable", "stacktrace": ["Traceback (most recent call last):\n", "  File \"d:\\work\\personal_project\\FlawlessAPI\\router.py\", line 471, in add_route\n    responses = self._get_response_schema(return_type, docstring)\n", "  File \"d:\\work\\personal_project\\FlawlessAPI\\router.py\", line 582, in _get_response_schema\n    for return_doc in docstring.returns:\n", "TypeError: 'DocstringReturns' object is not iterable\n"]}}
{"timestamp": "2024-11-09T23:18:52.032505", "level": "WARNING", "logger": "flawless_api", "message": "Failed to generate API docs for /_traces: 'DocstringReturns' object is not iterable", "module": "router", "line": 490, "exception": {"type": "TypeError", "message": "'DocstringReturns' object is not iterable", "stacktrace": ["Traceback (most recent call last):\n", "  File \"d:\\work\\personal_project\\FlawlessAPI\\router.py\", line 471, in add_route\n    responses = self._get_response_schema(return_type, docstring)\n", "  File \"d:\\work\\personal_project\\FlawlessAPI\\router.py\", line 582, in _get_response_schema\n    for return_doc in docstring.returns:\n", "TypeError: 'DocstringReturns' object is not iterable\n"]}}
{"timestamp": "2024-11-09T23:18:52.035373", "level": "WARNING", "logger": "flawless_api", "message": "Failed to generate API docs for /_health: 'DocstringReturns' object is not iterable", "module": "router", "line": 490, "exception": {"type": "TypeError", "message": "'DocstringReturns' object is not iterable", "stacktrace": ["Traceback (most recent call last):\n", "  File \"d:\\work\\personal_project\\FlawlessAPI\\router.py\", line 471, in add_route\n    responses = self._get_response_schema(return_type, docstring)\n", "  File \"d:\\work\\personal_project\\FlawlessAPI\\router.py\", line 582, in _get_response_schema\n    for return_doc in docstring.returns:\n", "TypeError: 'DocstringReturns' object is not iterable\n"]}}
{"timestamp": "2024-11-09T23:18:52.037831", "level": "WARNING", "logger": "flawless_api", "message": "Failed to generate API docs for /_info: 'DocstringReturns' object is not iterable", "module": "router", "line": 490, "exception": {"type": "TypeError", "message": "'DocstringReturns' object is not iterable", "stacktrace": ["Traceback (most recent call last):\n", "  File \"d:\\work\\personal_project\\FlawlessAPI\\router.py\", line 471, in add_route\n    responses = self._get_response_schema(return_type, docstring)\n", "  File \"d:\\work\\personal_project\\FlawlessAPI\\router.py\", line 582, in _get_response_schema\n    for return_doc in docstring.returns:\n", "TypeError: 'DocstringReturns' object is not iterable\n"]}}
{"timestamp": "2024-11-09T23:18:52.040939", "level": "WARNING", "logger": "flawless_api", "message": "Failed to generate API docs for /users/{id}: 'AutoDocGenerator' object has no attribute 'add_endpoint'", "module": "router", "line": 490, "exception": {"type": "AttributeError", "message": "'AutoDocGenerator' object has no attribute 'add_endpoint'", "stacktrace": ["Traceback (most recent call last):\n", "  File \"d:\\work\\personal_project\\FlawlessAPI\\router.py\", line 486, in add_route\n    self.auto_docs.add_endpoint(endpoint)\n", "AttributeError: 'AutoDocGenerator' object has no attribute 'add_endpoint'\n"]}}
{"timestamp": "2024-11-09T23:18:52.044946", "level": "WARNING", "logger": "flawless_api", "message": "Failed to generate API docs for /users: 'AutoDocGenerator' object has no attribute 'add_endpoint'", "module": "router", "line": 490, "exception": {"type": "AttributeError", "message": "'AutoDocGenerator' object has no attribute 'add_endpoint'", "stacktrace": ["Traceback (most recent call last):\n", "  File \"d:\\work\\personal_project\\FlawlessAPI\\router.py\", line 486, in add_route\n    self.auto_docs.add_endpoint(endpoint)\n", "AttributeError: 'AutoDocGenerator' object has no attribute 'add_endpoint'\n"]}}
{"timestamp": "2024-11-09T23:18:52.049616", "level": "WARNING", "logger": "flawless_api", "message": "Failed to generate API docs for /upload: 'AutoDocGenerator' object has no attribute 'add_endpoint'", "module": "router", "line": 490, "exception": {"type": "AttributeError", "message": "'AutoDocGenerator' object has no attribute 'add_endpoint'", "stacktrace": ["Traceback (most recent call last):\n", "  File \"d:\\work\\personal_project\\FlawlessAPI\\router.py\", line 486, in add_route\n    self.auto_docs.add_endpoint(endpoint)\n", "AttributeError: 'AutoDocGenerator' object has no attribute 'add_endpoint'\n"]}}
{"timestamp": "2024-11-09T23:18:52.054004", "level": "WARNING", "logger": "flawless_api", "message": "Failed to generate API docs for /page: 'AutoDocGenerator' object has no attribute 'add_endpoint'", "module": "router", "line": 490, "exception": {"type": "AttributeError", "message": "'AutoDocGenerator' object has no attribute 'add_endpoint'", "stacktrace": ["Traceback (most recent call last):\n", "  File \"d:\\work\\personal_project\\FlawlessAPI\\router.py\", line 486, in add_route\n    self.auto_docs.add_endpoint(endpoint)\n", "AttributeError: 'AutoDocGenerator' object has no attribute 'add_endpoint'\n"]}}
{"timestamp": "2024-11-09T23:18:52.058761", "level": "WARNING", "logger": "flawless_api", "message": "Failed to generate API docs for /message: 'AutoDocGenerator' object has no attribute 'add_endpoint'", "module": "router", "line": 490, "exception": {"type": "AttributeError", "message": "'AutoDocGenerator' object has no attribute 'add_endpoint'", "stacktrace": ["Traceback (most recent call last):\n", "  File \"d:\\work\\personal_project\\FlawlessAPI\\router.py\", line 486, in add_route\n    self.auto_docs.add_endpoint(endpoint)\n", "AttributeError: 'AutoDocGenerator' object has no attribute 'add_endpoint'\n"]}}
{"timestamp": "2024-11-09T23:18:52.062991", "level": "WARNING", "logger": "flawless_api", "message": "Failed to generate API docs for /tasks: 'AutoDocGenerator' object has no attribute 'add_endpoint'", "module": "router", "line": 490, "exception": {"type": "AttributeError", "message": "'AutoDocGenerator' object has no attribute 'add_endpoint'", "stacktrace": ["Traceback (most recent call last):\n", "  File \"d:\\work\\personal_project\\FlawlessAPI\\router.py\", line 486, in add_route\n    self.auto_docs.add_endpoint(endpoint)\n", "AttributeError: 'AutoDocGenerator' object has no attribute 'add_endpoint'\n"]}}
{"timestamp": "2024-11-09T23:18:52.067680", "level": "WARNING", "logger": "flawless_api", "message": "Failed to generate API docs for /docs: 'AutoDocGenerator' object has no attribute 'add_endpoint'", "module": "router", "line": 490, "exception": {"type": "AttributeError", "message": "'AutoDocGenerator' object has no attribute 'add_endpoint'", "stacktrace": ["Traceback (most recent call last):\n", "  File \"d:\\work\\personal_project\\FlawlessAPI\\router.py\", line 486, in add_route\n    self.auto_docs.add_endpoint(endpoint)\n", "AttributeError: 'AutoDocGenerator' object has no attribute 'add_endpoint'\n"]}}
{"timestamp": "2024-11-09T23:18:52.071680", "level": "WARNING", "logger": "flawless_api", "message": "Failed to generate API docs for /api/docs/spec: 'AutoDocGenerator' object has no attribute 'add_endpoint'", "module": "router", "line": 490, "exception": {"type": "AttributeError", "message": "'AutoDocGenerator' object has no attribute 'add_endpoint'", "stacktrace": ["Traceback (most recent call last):\n", "  File \"d:\\work\\personal_project\\FlawlessAPI\\router.py\", line 486, in add_route\n    self.auto_docs.add_endpoint(endpoint)\n", "AttributeError: 'AutoDocGenerator' object has no attribute 'add_endpoint'\n"]}}
{"timestamp": "2024-11-09T23:21:53.444347", "level": "WARNING", "logger": "flawless_api", "message": "Failed to generate API docs for /_metrics: 'DocstringReturns' object is not iterable", "module": "router", "line": 490, "exception": {"type": "TypeError", "message": "'DocstringReturns' object is not iterable", "stacktrace": ["Traceback (most recent call last):\n", "  File \"d:\\work\\personal_project\\FlawlessAPI\\router.py\", line 471, in add_route\n    responses = self._get_response_schema(return_type, docstring)\n", "  File \"d:\\work\\personal_project\\FlawlessAPI\\router.py\", line 582, in _get_response_schema\n    for return_doc in docstring.returns:\n", "TypeError: 'DocstringReturns' object is not iterable\n"]}}
{"timestamp": "2024-11-09T23:21:53.458239", "level": "WARNING", "logger": "flawless_api", "message": "Failed to generate API docs for /_traces: 'DocstringReturns' object is not iterable", "module": "router", "line": 490, "exception": {"type": "TypeError", "message": "'DocstringReturns' object is not iterable", "stacktrace": ["Traceback (most recent call last):\n", "  File \"d:\\work\\personal_project\\FlawlessAPI\\router.py\", line 471, in add_route\n    responses = self._get_response_schema(return_type, docstring)\n", "  File \"d:\\work\\personal_project\\FlawlessAPI\\router.py\", line 582, in _get_response_schema\n    for return_doc in docstring.returns:\n", "TypeError: 'DocstringReturns' object is not iterable\n"]}}
{"timestamp": "2024-11-09T23:21:53.461121", "level": "WARNING", "logger": "flawless_api", "message": "Failed to generate API docs for /_health: 'DocstringReturns' object is not iterable", "module": "router", "line": 490, "exception": {"type": "TypeError", "message": "'DocstringReturns' object is not iterable", "stacktrace": ["Traceback (most recent call last):\n", "  File \"d:\\work\\personal_project\\FlawlessAPI\\router.py\", line 471, in add_route\n    responses = self._get_response_schema(return_type, docstring)\n", "  File \"d:\\work\\personal_project\\FlawlessAPI\\router.py\", line 582, in _get_response_schema\n    for return_doc in docstring.returns:\n", "TypeError: 'DocstringReturns' object is not iterable\n"]}}
{"timestamp": "2024-11-09T23:21:53.465003", "level": "WARNING", "logger": "flawless_api", "message": "Failed to generate API docs for /_info: 'DocstringReturns' object is not iterable", "module": "router", "line": 490, "exception": {"type": "TypeError", "message": "'DocstringReturns' object is not iterable", "stacktrace": ["Traceback (most recent call last):\n", "  File \"d:\\work\\personal_project\\FlawlessAPI\\router.py\", line 471, in add_route\n    responses = self._get_response_schema(return_type, docstring)\n", "  File \"d:\\work\\personal_project\\FlawlessAPI\\router.py\", line 582, in _get_response_schema\n    for return_doc in docstring.returns:\n", "TypeError: 'DocstringReturns' object is not iterable\n"]}}
{"timestamp": "2024-11-09T23:22:16.220867", "level": "WARNING", "logger": "flawless_api", "message": "Failed to generate API docs for /_metrics: 'DocstringReturns' object is not iterable", "module": "router", "line": 492, "exception": {"type": "TypeError", "message": "'DocstringReturns' object is not iterable", "stacktrace": ["Traceback (most recent call last):\n", "  File \"d:\\work\\personal_project\\FlawlessAPI\\router.py\", line 473, in add_route\n    responses = self._get_response_schema(return_type, docstring)\n", "  File \"d:\\work\\personal_project\\FlawlessAPI\\router.py\", line 584, in _get_response_schema\n    for return_doc in docstring.returns:\n", "TypeError: 'DocstringReturns' object is not iterable\n"]}}
{"timestamp": "2024-11-09T23:22:16.227215", "level": "WARNING", "logger": "flawless_api", "message": "Failed to generate API docs for /_traces: 'DocstringReturns' object is not iterable", "module": "router", "line": 492, "exception": {"type": "TypeError", "message": "'DocstringReturns' object is not iterable", "stacktrace": ["Traceback (most recent call last):\n", "  File \"d:\\work\\personal_project\\FlawlessAPI\\router.py\", line 473, in add_route\n    responses = self._get_response_schema(return_type, docstring)\n", "  File \"d:\\work\\personal_project\\FlawlessAPI\\router.py\", line 584, in _get_response_schema\n    for return_doc in docstring.returns:\n", "TypeError: 'DocstringReturns' object is not iterable\n"]}}
{"timestamp": "2024-11-09T23:22:16.229907", "level": "WARNING", "logger": "flawless_api", "message": "Failed to generate API docs for /_health: 'DocstringReturns' object is not iterable", "module": "router", "line": 492, "exception": {"type": "TypeError", "message": "'DocstringReturns' object is not iterable", "stacktrace": ["Traceback (most recent call last):\n", "  File \"d:\\work\\personal_project\\FlawlessAPI\\router.py\", line 473, in add_route\n    responses = self._get_response_schema(return_type, docstring)\n", "  File \"d:\\work\\personal_project\\FlawlessAPI\\router.py\", line 584, in _get_response_schema\n    for return_doc in docstring.returns:\n", "TypeError: 'DocstringReturns' object is not iterable\n"]}}
{"timestamp": "2024-11-09T23:22:16.232605", "level": "WARNING", "logger": "flawless_api", "message": "Failed to generate API docs for /_info: 'DocstringReturns' object is not iterable", "module": "router", "line": 492, "exception": {"type": "TypeError", "message": "'DocstringReturns' object is not iterable", "stacktrace": ["Traceback (most recent call last):\n", "  File \"d:\\work\\personal_project\\FlawlessAPI\\router.py\", line 473, in add_route\n    responses = self._get_response_schema(return_type, docstring)\n", "  File \"d:\\work\\personal_project\\FlawlessAPI\\router.py\", line 584, in _get_response_schema\n    for return_doc in docstring.returns:\n", "TypeError: 'DocstringReturns' object is not iterable\n"]}}
{"timestamp": "2024-11-09T23:22:16.235314", "level": "WARNING", "logger": "flawless_api", "message": "Failed to generate API docs for /docs: __args__", "module": "router", "line": 492, "exception": {"type": "AttributeError", "message": "__args__", "stacktrace": ["Traceback (most recent call last):\n", "  File \"d:\\work\\personal_project\\FlawlessAPI\\router.py\", line 473, in add_route\n    responses = self._get_response_schema(return_type, docstring)\n", "  File \"d:\\work\\personal_project\\FlawlessAPI\\router.py\", line 548, in _get_response_schema\n    \"schema\": self._get_parameter_schema(return_type)\n", "  File \"d:\\work\\personal_project\\FlawlessAPI\\router.py\", line 529, in _get_parameter_schema\n    \"additionalProperties\": self._get_parameter_schema(param_type.__args__[1])\n", "  File \"D:\\work\\python\\python3.10.6\\lib\\typing.py\", line 984, in __getattr__\n    raise AttributeError(attr)\n", "AttributeError: __args__. Did you mean: '__ror__'?\n"]}}
{"timestamp": "2024-11-09T23:22:16.240531", "level": "WARNING", "logger": "flawless_api", "message": "Failed to generate API docs for /api/docs/spec: __args__", "module": "router", "line": 492, "exception": {"type": "AttributeError", "message": "__args__", "stacktrace": ["Traceback (most recent call last):\n", "  File \"d:\\work\\personal_project\\FlawlessAPI\\router.py\", line 473, in add_route\n    responses = self._get_response_schema(return_type, docstring)\n", "  File \"d:\\work\\personal_project\\FlawlessAPI\\router.py\", line 548, in _get_response_schema\n    \"schema\": self._get_parameter_schema(return_type)\n", "  File \"d:\\work\\personal_project\\FlawlessAPI\\router.py\", line 529, in _get_parameter_schema\n    \"additionalProperties\": self._get_parameter_schema(param_type.__args__[1])\n", "  File \"D:\\work\\python\\python3.10.6\\lib\\typing.py\", line 984, in __getattr__\n    raise AttributeError(attr)\n", "AttributeError: __args__. Did you mean: '__ror__'?\n"]}}
{"timestamp": "2024-11-09T23:22:16.246531", "level": "WARNING", "logger": "flawless_api", "message": "Failed to generate API docs for /users/{id}: 'DocstringReturns' object is not iterable", "module": "router", "line": 492, "exception": {"type": "TypeError", "message": "'DocstringReturns' object is not iterable", "stacktrace": ["Traceback (most recent call last):\n", "  File \"d:\\work\\personal_project\\FlawlessAPI\\router.py\", line 473, in add_route\n    responses = self._get_response_schema(return_type, docstring)\n", "  File \"d:\\work\\personal_project\\FlawlessAPI\\router.py\", line 584, in _get_response_schema\n    for return_doc in docstring.returns:\n", "TypeError: 'DocstringReturns' object is not iterable\n"]}}
{"timestamp": "2024-11-09T23:22:16.248556", "level": "WARNING", "logger": "flawless_api", "message": "Failed to generate API docs for /users: 'DocstringReturns' object is not iterable", "module": "router", "line": 492, "exception": {"type": "TypeError", "message": "'DocstringReturns' object is not iterable", "stacktrace": ["Traceback (most recent call last):\n", "  File \"d:\\work\\personal_project\\FlawlessAPI\\router.py\", line 473, in add_route\n    responses = self._get_response_schema(return_type, docstring)\n", "  File \"d:\\work\\personal_project\\FlawlessAPI\\router.py\", line 584, in _get_response_schema\n    for return_doc in docstring.returns:\n", "TypeError: 'DocstringReturns' object is not iterable\n"]}}
{"timestamp": "2024-11-09T23:22:16.251533", "level": "WARNING", "logger": "flawless_api", "message": "Failed to generate API docs for /users/{id}: 'DocstringReturns' object is not iterable", "module": "router", "line": 492, "exception": {"type": "TypeError", "message": "'DocstringReturns' object is not iterable", "stacktrace": ["Traceback (most recent call last):\n", "  File \"d:\\work\\personal_project\\FlawlessAPI\\router.py\", line 473, in add_route\n    responses = self._get_response_schema(return_type, docstring)\n", "  File \"d:\\work\\personal_project\\FlawlessAPI\\router.py\", line 584, in _get_response_schema\n    for return_doc in docstring.returns:\n", "TypeError: 'DocstringReturns' object is not iterable\n"]}}
{"timestamp": "2024-11-09T23:22:16.254531", "level": "WARNING", "logger": "flawless_api", "message": "Failed to generate API docs for /users: 'DocstringReturns' object is not iterable", "module": "router", "line": 492, "exception": {"type": "TypeError", "message": "'DocstringReturns' object is not iterable", "stacktrace": ["Traceback (most recent call last):\n", "  File \"d:\\work\\personal_project\\FlawlessAPI\\router.py\", line 473, in add_route\n    responses = self._get_response_schema(return_type, docstring)\n", "  File \"d:\\work\\personal_project\\FlawlessAPI\\router.py\", line 584, in _get_response_schema\n    for return_doc in docstring.returns:\n", "TypeError: 'DocstringReturns' object is not iterable\n"]}}
{"timestamp": "2024-11-09T23:22:23.025702", "level": "WARNING", "logger": "flawless_api", "message": "Failed to generate API docs for /_metrics: 'DocstringReturns' object is not iterable", "module": "router", "line": 492, "exception": {"type": "TypeError", "message": "'DocstringReturns' object is not iterable", "stacktrace": ["Traceback (most recent call last):\n", "  File \"d:\\work\\personal_project\\FlawlessAPI\\router.py\", line 473, in add_route\n    responses = self._get_response_schema(return_type, docstring)\n", "  File \"d:\\work\\personal_project\\FlawlessAPI\\router.py\", line 584, in _get_response_schema\n    for return_doc in docstring.returns:\n", "TypeError: 'DocstringReturns' object is not iterable\n"]}}
{"timestamp": "2024-11-09T23:22:23.038621", "level": "WARNING", "logger": "flawless_api", "message": "Failed to generate API docs for /_traces: 'DocstringReturns' object is not iterable", "module": "router", "line": 492, "exception": {"type": "TypeError", "message": "'DocstringReturns' object is not iterable", "stacktrace": ["Traceback (most recent call last):\n", "  File \"d:\\work\\personal_project\\FlawlessAPI\\router.py\", line 473, in add_route\n    responses = self._get_response_schema(return_type, docstring)\n", "  File \"d:\\work\\personal_project\\FlawlessAPI\\router.py\", line 584, in _get_response_schema\n    for return_doc in docstring.returns:\n", "TypeError: 'DocstringReturns' object is not iterable\n"]}}
{"timestamp": "2024-11-09T23:22:23.041264", "level": "WARNING", "logger": "flawless_api", "message": "Failed to generate API docs for /_health: 'DocstringReturns' object is not iterable", "module": "router", "line": 492, "exception": {"type": "TypeError", "message": "'DocstringReturns' object is not iterable", "stacktrace": ["Traceback (most recent call last):\n", "  File \"d:\\work\\personal_project\\FlawlessAPI\\router.py\", line 473, in add_route\n    responses = self._get_response_schema(return_type, docstring)\n", "  File \"d:\\work\\personal_project\\FlawlessAPI\\router.py\", line 584, in _get_response_schema\n    for return_doc in docstring.returns:\n", "TypeError: 'DocstringReturns' object is not iterable\n"]}}
{"timestamp": "2024-11-09T23:22:23.042836", "level": "WARNING", "logger": "flawless_api", "message": "Failed to generate API docs for /_info: 'DocstringReturns' object is not iterable", "module": "router", "line": 492, "exception": {"type": "TypeError", "message": "'DocstringReturns' object is not iterable", "stacktrace": ["Traceback (most recent call last):\n", "  File \"d:\\work\\personal_project\\FlawlessAPI\\router.py\", line 473, in add_route\n    responses = self._get_response_schema(return_type, docstring)\n", "  File \"d:\\work\\personal_project\\FlawlessAPI\\router.py\", line 584, in _get_response_schema\n    for return_doc in docstring.returns:\n", "TypeError: 'DocstringReturns' object is not iterable\n"]}}
{"timestamp": "2024-11-09T23:22:23.046051", "level": "WARNING", "logger": "flawless_api", "message": "Failed to generate API docs for /docs: __args__", "module": "router", "line": 492, "exception": {"type": "AttributeError", "message": "__args__", "stacktrace": ["Traceback (most recent call last):\n", "  File \"d:\\work\\personal_project\\FlawlessAPI\\router.py\", line 473, in add_route\n    responses = self._get_response_schema(return_type, docstring)\n", "  File \"d:\\work\\personal_project\\FlawlessAPI\\router.py\", line 548, in _get_response_schema\n    \"schema\": self._get_parameter_schema(return_type)\n", "  File \"d:\\work\\personal_project\\FlawlessAPI\\router.py\", line 529, in _get_parameter_schema\n    \"additionalProperties\": self._get_parameter_schema(param_type.__args__[1])\n", "  File \"D:\\work\\python\\python3.10.6\\lib\\typing.py\", line 984, in __getattr__\n    raise AttributeError(attr)\n", "AttributeError: __args__. Did you mean: '__ror__'?\n"]}}
{"timestamp": "2024-11-09T23:22:23.050708", "level": "WARNING", "logger": "flawless_api", "message": "Failed to generate API docs for /api/docs/spec: __args__", "module": "router", "line": 492, "exception": {"type": "AttributeError", "message": "__args__", "stacktrace": ["Traceback (most recent call last):\n", "  File \"d:\\work\\personal_project\\FlawlessAPI\\router.py\", line 473, in add_route\n    responses = self._get_response_schema(return_type, docstring)\n", "  File \"d:\\work\\personal_project\\FlawlessAPI\\router.py\", line 548, in _get_response_schema\n    \"schema\": self._get_parameter_schema(return_type)\n", "  File \"d:\\work\\personal_project\\FlawlessAPI\\router.py\", line 529, in _get_parameter_schema\n    \"additionalProperties\": self._get_parameter_schema(param_type.__args__[1])\n", "  File \"D:\\work\\python\\python3.10.6\\lib\\typing.py\", line 984, in __getattr__\n    raise AttributeError(attr)\n", "AttributeError: __args__. Did you mean: '__ror__'?\n"]}}
{"timestamp": "2024-11-09T23:22:23.054697", "level": "WARNING", "logger": "flawless_api", "message": "Failed to generate API docs for /users/{id}: 'DocstringReturns' object is not iterable", "module": "router", "line": 492, "exception": {"type": "TypeError", "message": "'DocstringReturns' object is not iterable", "stacktrace": ["Traceback (most recent call last):\n", "  File \"d:\\work\\personal_project\\FlawlessAPI\\router.py\", line 473, in add_route\n    responses = self._get_response_schema(return_type, docstring)\n", "  File \"d:\\work\\personal_project\\FlawlessAPI\\router.py\", line 584, in _get_response_schema\n    for return_doc in docstring.returns:\n", "TypeError: 'DocstringReturns' object is not iterable\n"]}}
{"timestamp": "2024-11-09T23:22:23.057386", "level": "WARNING", "logger": "flawless_api", "message": "Failed to generate API docs for /users: 'DocstringReturns' object is not iterable", "module": "router", "line": 492, "exception": {"type": "TypeError", "message": "'DocstringReturns' object is not iterable", "stacktrace": ["Traceback (most recent call last):\n", "  File \"d:\\work\\personal_project\\FlawlessAPI\\router.py\", line 473, in add_route\n    responses = self._get_response_schema(return_type, docstring)\n", "  File \"d:\\work\\personal_project\\FlawlessAPI\\router.py\", line 584, in _get_response_schema\n    for return_doc in docstring.returns:\n", "TypeError: 'DocstringReturns' object is not iterable\n"]}}
{"timestamp": "2024-11-09T23:22:23.060040", "level": "WARNING", "logger": "flawless_api", "message": "Failed to generate API docs for /users/{id}: 'DocstringReturns' object is not iterable", "module": "router", "line": 492, "exception": {"type": "TypeError", "message": "'DocstringReturns' object is not iterable", "stacktrace": ["Traceback (most recent call last):\n", "  File \"d:\\work\\personal_project\\FlawlessAPI\\router.py\", line 473, in add_route\n    responses = self._get_response_schema(return_type, docstring)\n", "  File \"d:\\work\\personal_project\\FlawlessAPI\\router.py\", line 584, in _get_response_schema\n    for return_doc in docstring.returns:\n", "TypeError: 'DocstringReturns' object is not iterable\n"]}}
{"timestamp": "2024-11-09T23:22:23.062162", "level": "WARNING", "logger": "flawless_api", "message": "Failed to generate API docs for /users: 'DocstringReturns' object is not iterable", "module": "router", "line": 492, "exception": {"type": "TypeError", "message": "'DocstringReturns' object is not iterable", "stacktrace": ["Traceback (most recent call last):\n", "  File \"d:\\work\\personal_project\\FlawlessAPI\\router.py\", line 473, in add_route\n    responses = self._get_response_schema(return_type, docstring)\n", "  File \"d:\\work\\personal_project\\FlawlessAPI\\router.py\", line 584, in _get_response_schema\n    for return_doc in docstring.returns:\n", "TypeError: 'DocstringReturns' object is not iterable\n"]}}
{"timestamp": "2024-11-09T23:42:59.225196", "level": "WARNING", "logger": "flawless_api", "message": "Failed to generate API docs for /users/{id}: argument of type 'Parameter' is not iterable", "module": "router", "line": 505, "exception": {"type": "TypeError", "message": "argument of type 'Parameter' is not iterable", "stacktrace": ["Traceback (most recent call last):\n", "  File \"d:\\work\\personal_project\\FlawlessAPI\\router.py\", line 459, in add_route\n    elif param_name in param:  # \u8def\u5f84\u53c2\u6570\n", "TypeError: argument of type 'Parameter' is not iterable\n"]}}
{"timestamp": "2024-11-09T23:42:59.230194", "level": "WARNING", "logger": "flawless_api", "message": "Failed to generate API docs for /users: argument of type 'Parameter' is not iterable", "module": "router", "line": 505, "exception": {"type": "TypeError", "message": "argument of type 'Parameter' is not iterable", "stacktrace": ["Traceback (most recent call last):\n", "  File \"d:\\work\\personal_project\\FlawlessAPI\\router.py\", line 459, in add_route\n    elif param_name in param:  # \u8def\u5f84\u53c2\u6570\n", "TypeError: argument of type 'Parameter' is not iterable\n"]}}
{"timestamp": "2024-11-10T00:23:41.945054", "level": "WARNING", "logger": "flawless_api", "message": "Failed to generate API docs for /_metrics: name 'params' is not defined", "module": "router", "line": 519, "exception": {"type": "NameError", "message": "name 'params' is not defined", "stacktrace": ["Traceback (most recent call last):\n", "  File \"d:\\work\\personal_project\\FlawlessAPI\\router.py\", line 468, in add_route\n    parameters = params or []\n", "NameError: name 'params' is not defined. Did you mean: 'parts'?\n"]}}
{"timestamp": "2024-11-10T00:23:41.949679", "level": "WARNING", "logger": "flawless_api", "message": "Failed to generate API docs for /_traces: name 'params' is not defined", "module": "router", "line": 519, "exception": {"type": "NameError", "message": "name 'params' is not defined", "stacktrace": ["Traceback (most recent call last):\n", "  File \"d:\\work\\personal_project\\FlawlessAPI\\router.py\", line 468, in add_route\n    parameters = params or []\n", "NameError: name 'params' is not defined. Did you mean: 'parts'?\n"]}}
{"timestamp": "2024-11-10T00:23:41.952946", "level": "WARNING", "logger": "flawless_api", "message": "Failed to generate API docs for /_health: name 'params' is not defined", "module": "router", "line": 519, "exception": {"type": "NameError", "message": "name 'params' is not defined", "stacktrace": ["Traceback (most recent call last):\n", "  File \"d:\\work\\personal_project\\FlawlessAPI\\router.py\", line 468, in add_route\n    parameters = params or []\n", "NameError: name 'params' is not defined. Did you mean: 'parts'?\n"]}}
{"timestamp": "2024-11-10T00:23:41.957754", "level": "WARNING", "logger": "flawless_api", "message": "Failed to generate API docs for /_info: name 'params' is not defined", "module": "router", "line": 519, "exception": {"type": "NameError", "message": "name 'params' is not defined", "stacktrace": ["Traceback (most recent call last):\n", "  File \"d:\\work\\personal_project\\FlawlessAPI\\router.py\", line 468, in add_route\n    parameters = params or []\n", "NameError: name 'params' is not defined. Did you mean: 'parts'?\n"]}}
{"timestamp": "2024-11-10T00:23:41.961760", "level": "WARNING", "logger": "flawless_api", "message": "Failed to generate API docs for /docs: name 'params' is not defined", "module": "router", "line": 519, "exception": {"type": "NameError", "message": "name 'params' is not defined", "stacktrace": ["Traceback (most recent call last):\n", "  File \"d:\\work\\personal_project\\FlawlessAPI\\router.py\", line 468, in add_route\n    parameters = params or []\n", "NameError: name 'params' is not defined. Did you mean: 'parts'?\n"]}}
{"timestamp": "2024-11-10T00:23:41.966195", "level": "WARNING", "logger": "flawless_api", "message": "Failed to generate API docs for /api/docs/spec: name 'params' is not defined", "module": "router", "line": 519, "exception": {"type": "NameError", "message": "name 'params' is not defined", "stacktrace": ["Traceback (most recent call last):\n", "  File \"d:\\work\\personal_project\\FlawlessAPI\\router.py\", line 468, in add_route\n    parameters = params or []\n", "NameError: name 'params' is not defined. Did you mean: 'parts'?\n"]}}
{"timestamp": "2024-11-10T00:23:42.006964", "level": "WARNING", "logger": "flawless_api", "message": "Failed to generate API docs for /users/{id}: name 'params' is not defined", "module": "router", "line": 519, "exception": {"type": "NameError", "message": "name 'params' is not defined", "stacktrace": ["Traceback (most recent call last):\n", "  File \"d:\\work\\personal_project\\FlawlessAPI\\router.py\", line 468, in add_route\n    parameters = params or []\n", "NameError: name 'params' is not defined. Did you mean: 'parts'?\n"]}}
{"timestamp": "2024-11-10T00:23:42.011088", "level": "WARNING", "logger": "flawless_api", "message": "Failed to generate API docs for /users: name 'params' is not defined", "module": "router", "line": 519, "exception": {"type": "NameError", "message": "name 'params' is not defined", "stacktrace": ["Traceback (most recent call last):\n", "  File \"d:\\work\\personal_project\\FlawlessAPI\\router.py\", line 468, in add_route\n    parameters = params or []\n", "NameError: name 'params' is not defined. Did you mean: 'parts'?\n"]}}
{"timestamp": "2024-11-10T00:23:42.014088", "level": "WARNING", "logger": "flawless_api", "message": "Failed to generate API docs for /upload: name 'params' is not defined", "module": "router", "line": 519, "exception": {"type": "NameError", "message": "name 'params' is not defined", "stacktrace": ["Traceback (most recent call last):\n", "  File \"d:\\work\\personal_project\\FlawlessAPI\\router.py\", line 468, in add_route\n    parameters = params or []\n", "NameError: name 'params' is not defined. Did you mean: 'parts'?\n"]}}
{"timestamp": "2024-11-10T00:23:42.019481", "level": "WARNING", "logger": "flawless_api", "message": "Failed to generate API docs for /page: name 'params' is not defined", "module": "router", "line": 519, "exception": {"type": "NameError", "message": "name 'params' is not defined", "stacktrace": ["Traceback (most recent call last):\n", "  File \"d:\\work\\personal_project\\FlawlessAPI\\router.py\", line 468, in add_route\n    parameters = params or []\n", "NameError: name 'params' is not defined. Did you mean: 'parts'?\n"]}}
{"timestamp": "2024-11-10T00:23:42.026697", "level": "WARNING", "logger": "flawless_api", "message": "Failed to generate API docs for /message: name 'params' is not defined", "module": "router", "line": 519, "exception": {"type": "NameError", "message": "name 'params' is not defined", "stacktrace": ["Traceback (most recent call last):\n", "  File \"d:\\work\\personal_project\\FlawlessAPI\\router.py\", line 468, in add_route\n    parameters = params or []\n", "NameError: name 'params' is not defined. Did you mean: 'parts'?\n"]}}
{"timestamp": "2024-11-10T00:23:42.033568", "level": "WARNING", "logger": "flawless_api", "message": "Failed to generate API docs for /tasks: name 'params' is not defined", "module": "router", "line": 519, "exception": {"type": "NameError", "message": "name 'params' is not defined", "stacktrace": ["Traceback (most recent call last):\n", "  File \"d:\\work\\personal_project\\FlawlessAPI\\router.py\", line 468, in add_route\n    parameters = params or []\n", "NameError: name 'params' is not defined. Did you mean: 'parts'?\n"]}}
{"timestamp": "2024-11-10T00:27:29.613818", "level": "WARNING", "logger": "flawless_api", "message": "Failed to generate API docs for /_metrics: FlawlessAPI._get_response_schema() missing 1 required positional argument: 'docstring'", "module": "router", "line": 516, "exception": {"type": "TypeError", "message": "FlawlessAPI._get_response_schema() missing 1 required positional argument: 'docstring'", "stacktrace": ["Traceback (most recent call last):\n", "  File \"d:\\work\\personal_project\\FlawlessAPI\\router.py\", line 508, in add_route\n    responses=self._get_response_schema(handler),\n", "TypeError: FlawlessAPI._get_response_schema() missing 1 required positional argument: 'docstring'\n"]}}
{"timestamp": "2024-11-10T00:27:29.626976", "level": "WARNING", "logger": "flawless_api", "message": "Failed to generate API docs for /_traces: FlawlessAPI._get_response_schema() missing 1 required positional argument: 'docstring'", "module": "router", "line": 516, "exception": {"type": "TypeError", "message": "FlawlessAPI._get_response_schema() missing 1 required positional argument: 'docstring'", "stacktrace": ["Traceback (most recent call last):\n", "  File \"d:\\work\\personal_project\\FlawlessAPI\\router.py\", line 508, in add_route\n    responses=self._get_response_schema(handler),\n", "TypeError: FlawlessAPI._get_response_schema() missing 1 required positional argument: 'docstring'\n"]}}
{"timestamp": "2024-11-10T00:27:29.629975", "level": "WARNING", "logger": "flawless_api", "message": "Failed to generate API docs for /_health: FlawlessAPI._get_response_schema() missing 1 required positional argument: 'docstring'", "module": "router", "line": 516, "exception": {"type": "TypeError", "message": "FlawlessAPI._get_response_schema() missing 1 required positional argument: 'docstring'", "stacktrace": ["Traceback (most recent call last):\n", "  File \"d:\\work\\personal_project\\FlawlessAPI\\router.py\", line 508, in add_route\n    responses=self._get_response_schema(handler),\n", "TypeError: FlawlessAPI._get_response_schema() missing 1 required positional argument: 'docstring'\n"]}}
{"timestamp": "2024-11-10T00:27:29.631979", "level": "WARNING", "logger": "flawless_api", "message": "Failed to generate API docs for /_info: FlawlessAPI._get_response_schema() missing 1 required positional argument: 'docstring'", "module": "router", "line": 516, "exception": {"type": "TypeError", "message": "FlawlessAPI._get_response_schema() missing 1 required positional argument: 'docstring'", "stacktrace": ["Traceback (most recent call last):\n", "  File \"d:\\work\\personal_project\\FlawlessAPI\\router.py\", line 508, in add_route\n    responses=self._get_response_schema(handler),\n", "TypeError: FlawlessAPI._get_response_schema() missing 1 required positional argument: 'docstring'\n"]}}
{"timestamp": "2024-11-10T00:27:29.635069", "level": "WARNING", "logger": "flawless_api", "message": "Failed to generate API docs for /docs: FlawlessAPI._get_response_schema() missing 1 required positional argument: 'docstring'", "module": "router", "line": 516, "exception": {"type": "TypeError", "message": "FlawlessAPI._get_response_schema() missing 1 required positional argument: 'docstring'", "stacktrace": ["Traceback (most recent call last):\n", "  File \"d:\\work\\personal_project\\FlawlessAPI\\router.py\", line 508, in add_route\n    responses=self._get_response_schema(handler),\n", "TypeError: FlawlessAPI._get_response_schema() missing 1 required positional argument: 'docstring'\n"]}}
{"timestamp": "2024-11-10T00:27:29.638575", "level": "WARNING", "logger": "flawless_api", "message": "Failed to generate API docs for /api/docs/spec: FlawlessAPI._get_response_schema() missing 1 required positional argument: 'docstring'", "module": "router", "line": 516, "exception": {"type": "TypeError", "message": "FlawlessAPI._get_response_schema() missing 1 required positional argument: 'docstring'", "stacktrace": ["Traceback (most recent call last):\n", "  File \"d:\\work\\personal_project\\FlawlessAPI\\router.py\", line 508, in add_route\n    responses=self._get_response_schema(handler),\n", "TypeError: FlawlessAPI._get_response_schema() missing 1 required positional argument: 'docstring'\n"]}}
{"timestamp": "2024-11-10T00:27:29.686341", "level": "WARNING", "logger": "flawless_api", "message": "Failed to generate API docs for /users/{id}: FlawlessAPI._get_response_schema() missing 1 required positional argument: 'docstring'", "module": "router", "line": 516, "exception": {"type": "TypeError", "message": "FlawlessAPI._get_response_schema() missing 1 required positional argument: 'docstring'", "stacktrace": ["Traceback (most recent call last):\n", "  File \"d:\\work\\personal_project\\FlawlessAPI\\router.py\", line 508, in add_route\n    responses=self._get_response_schema(handler),\n", "TypeError: FlawlessAPI._get_response_schema() missing 1 required positional argument: 'docstring'\n"]}}
{"timestamp": "2024-11-10T00:27:29.689029", "level": "WARNING", "logger": "flawless_api", "message": "Failed to generate API docs for /users: FlawlessAPI._get_response_schema() missing 1 required positional argument: 'docstring'", "module": "router", "line": 516, "exception": {"type": "TypeError", "message": "FlawlessAPI._get_response_schema() missing 1 required positional argument: 'docstring'", "stacktrace": ["Traceback (most recent call last):\n", "  File \"d:\\work\\personal_project\\FlawlessAPI\\router.py\", line 508, in add_route\n    responses=self._get_response_schema(handler),\n", "TypeError: FlawlessAPI._get_response_schema() missing 1 required positional argument: 'docstring'\n"]}}
{"timestamp": "2024-11-10T00:27:29.692026", "level": "WARNING", "logger": "flawless_api", "message": "Failed to generate API docs for /upload: FlawlessAPI._get_response_schema() missing 1 required positional argument: 'docstring'", "module": "router", "line": 516, "exception": {"type": "TypeError", "message": "FlawlessAPI._get_response_schema() missing 1 required positional argument: 'docstring'", "stacktrace": ["Traceback (most recent call last):\n", "  File \"d:\\work\\personal_project\\FlawlessAPI\\router.py\", line 508, in add_route\n    responses=self._get_response_schema(handler),\n", "TypeError: FlawlessAPI._get_response_schema() missing 1 required positional argument: 'docstring'\n"]}}
{"timestamp": "2024-11-10T00:27:29.694029", "level": "WARNING", "logger": "flawless_api", "message": "Failed to generate API docs for /page: FlawlessAPI._get_response_schema() missing 1 required positional argument: 'docstring'", "module": "router", "line": 516, "exception": {"type": "TypeError", "message": "FlawlessAPI._get_response_schema() missing 1 required positional argument: 'docstring'", "stacktrace": ["Traceback (most recent call last):\n", "  File \"d:\\work\\personal_project\\FlawlessAPI\\router.py\", line 508, in add_route\n    responses=self._get_response_schema(handler),\n", "TypeError: FlawlessAPI._get_response_schema() missing 1 required positional argument: 'docstring'\n"]}}
{"timestamp": "2024-11-10T00:27:29.695025", "level": "WARNING", "logger": "flawless_api", "message": "Failed to generate API docs for /message: FlawlessAPI._get_response_schema() missing 1 required positional argument: 'docstring'", "module": "router", "line": 516, "exception": {"type": "TypeError", "message": "FlawlessAPI._get_response_schema() missing 1 required positional argument: 'docstring'", "stacktrace": ["Traceback (most recent call last):\n", "  File \"d:\\work\\personal_project\\FlawlessAPI\\router.py\", line 508, in add_route\n    responses=self._get_response_schema(handler),\n", "TypeError: FlawlessAPI._get_response_schema() missing 1 required positional argument: 'docstring'\n"]}}
{"timestamp": "2024-11-10T00:27:29.697134", "level": "WARNING", "logger": "flawless_api", "message": "Failed to generate API docs for /tasks: FlawlessAPI._get_response_schema() missing 1 required positional argument: 'docstring'", "module": "router", "line": 516, "exception": {"type": "TypeError", "message": "FlawlessAPI._get_response_schema() missing 1 required positional argument: 'docstring'", "stacktrace": ["Traceback (most recent call last):\n", "  File \"d:\\work\\personal_project\\FlawlessAPI\\router.py\", line 508, in add_route\n    responses=self._get_response_schema(handler),\n", "TypeError: FlawlessAPI._get_response_schema() missing 1 required positional argument: 'docstring'\n"]}}
